services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - spring-boot-network

  app:
    container_name: spring-app
    image: springrest:v1.0.1
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres

volumes:
  postgres_data:
networks:
  spring-boot-network:
    driver: bridge

