# MySQL connection properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: AS0mIbmP7pu3cCMwBcsy
    # mysql://root:AS0mIbmP7pu3cCMwBcsy@containers-us-west-162.railway.app:6726/railway
    url: jdbc:mysql://containers-us-west-162.railway.app:6726/railwaycreateDatabaseIfNotExist=true&createTableIfNotExist=true&allowPublicKeyRetrieval=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # Log JPA queries
    # Comment this in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Drop and create new tables (create, create-drop, validate, update)
        # Only for testing purposes - comment this in production
        hbm2ddl:
          auto: update
  # Spring Mail Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: devmail026@gmail.com
    password: xpadoeylemcxgjjp # Generated Google App password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectionTimeout: 5000
          timeout: 3000
          writeTimeout: 5000

# Actuator HttpTrace Endpoint Setup
# tracing all the requests that hit our services and collect this information to analyze it later.
management:
  endpoints:
    web:
      exposure:
        include: httptrace

##### API PROPERTIES ######
assigndevelopers:
  app:
    # 1 DAY / 24 HOURS = 86400000
    jwtExpirationMs: 86400000
    # 7 DAYS / 168 HOURS = 604800000
    refreshExpirationMs: 604800000
    # 10 MINUTES = 600000
    emailVerifyExpirationMs: 600000
    # Change to Remote host in Production
    hostName: " https://springbootdemo-production-abe5.up.railway.app/api/v1/auth"
    # Random 256 bit 32 Byte Hex (HS256) Key
    jwtSecret: 8e435e4f2a530f331a64948e38cd4e063ddac96447c52011f611b4c8d853ea9e
# Display SpringDoc Swagger-Ui OpenAPI endpoint
springdoc:
  # Display spring-boot-actuator endpoints in SpringDoc Swagger-Ui
  show-actuator: true
