Server:
  port: 8080
# MySQL connection properties
spring:
  sql:
    init:
      # SQL is written to be idempotent so this is safe
      mode: always
  datasource:
    # AWS RDS PostgreSQL Connection
    url: jdbc:postgresql://database-1.chvctnpsl8yc.us-east-1.rds.amazonaws.com:5432/demo_db
    # Docker Container - PostgreSQL Connection
    #url: jdbc:postgresql://postgres-sql:5432/demo_db
    username: postgres
    password: Winner=2021
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Spring Mail Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: devmail026@gmail.com
    password: xpadoeylemcxgjjp # Generated Google App password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectionTimeout: 5000
          timeout: 3000
          writeTimeout: 5000

# Actuator HttpTrace Endpoint Setup
management:
  endpoints:
    web:
      # Expose & monitor Client HTTP Calls in the SB-Admin Server
      exposure:
        # Expose & monitor All endpoints
        include: "*" # httptrace
  endpoint:
    health:
      show-components: always
    shutdown:
      enabled: true
    refresh:
      enabled: true
    env:
      enabled: true

# API PROPERTIES
assigndevelopers:
  app:
    # 1 DAY / 24 HOURS = 86400000
    jwtExpirationMs: 86400000
    # 7 DAYS / 168 HOURS = 604800000
    refreshExpirationMs: 604800000
    # 10 MINUTES = 600000
    emailVerifyExpirationMs: 600000
    # Change to Remote host in Production
    hostName: " /api/v1/auth"
    # hostName: " http://localhost:8080/api/v1/auth"
    # Random 256 bit 32 Byte Hex (HS256) Key
    jwtSecret: 8e435e4f2a530f331a64948e38cd4e063ddac96447c52011f611b4c8d853ea9e

    # basic auth credentials
    security:
      usernameAdmin: admin@gmail.com
      passwordAdmin: 12345

# Display SpringDoc Swagger-Ui OpenAPI endpoint
springdoc:
  # Display spring-boot-actuator endpoints in SpringDoc Swagger-Ui
  show-actuator: true
  # Write logs into library-api-steve.log file

logging:
  file:
    name: library-api-steve.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  logback:
    rollingpolicy:
      max-history: 20
      max-file-size: 20MB

